### ISSUE TITLE
Unmatched ROIs in predicted segmentation and provided FastSurfer_ColorLUT.tsv

### ISSUE THREAD

**Issue by gmeng92** [Deep-MI/FastSurfer#514] opened 2024-04-19 19:04 UTC
## Question/Support Request
I run the FastSurferCNN (--seg-only) to get the DKT atlas segementaion given t1W MR images. 

By using my local images, I ended up get 88 unique ROI labels(including the background = 0), which is inconsistent with the ROI list as /coifg/FastSurfer_ColorLUT.tsv. Then I followed your tutorial to run the --seg-only code using the image you provided as in (https://github.com/Deep-MI/FastSurfer/blob/dev/Tutorial/Tutorial_FastSurferCNN_QuickSeg.ipynb), it turns out to 88 unique ROI labels again. 

So the provided labels (in the tsp) seems unmatched with the predicted labels (from segmented images). Beisides, I noticed that in the tutorial notebook, I find the cell under "Click3" saying that 95 predicted labels are expected. And all those mismatches happen to be on the right hemisphere cortex. Can you help me elaborate those unmatched labels? Thanks

## Screenshots / Log files
![Screenshot 2024-04-19 at 1 57 17 PM](https://github.com/Deep-MI/FastSurfer/assets/36212932/caa415e4-5cf0-4cc3-ac94-a95e9616b575)

**Comment by dkuegler** [comment] 2024-04-19 20:06
That is expected and correct behavior.
The classes in config/FastSurfer_ColorLUT.tsv are the labels that are predicted by the neural network, but we do a Postprocessing step after. For example, some labels get laterilized there (which is why you have mismatched labels on one side).

Moreover, you will see that the indices of the segmentation classes are also very different between the FastSurfer_ColorLUT.tsv and the output image.

**Comment by gmeng92** [comment] 2024-04-19 20:29
Thanks for the quick reply!  So in practice, we will still use the file config/FastSurfer_ColorLUT.tsv for training/inferencing through FastSurferCNN, right?  And what happens in the Postprocessing step after?

 I noticed only the right hemisphere is influenced and many important regions of interest (like rh-postcentral etc.) are missing in the segmentation. I further compared the performance between FastSurferCNN and FreeSurfer on 11 T1 images. The correlation indicates fastssurfer can do a better job on lh-ctx segmentation compared to the rh-ctx.  That makes me hesitate to use the segmented results as qualified "features" for following analysis.

<img width="1098" alt="Screenshot 2024-04-19 at 3 20 50 PM" src="https://github.com/Deep-MI/FastSurfer/assets/36212932/30de7e84-e56b-4b66-b0c7-ee6bcf12f1de">
<img width="1095" alt="Screenshot 2024-04-19 at 3 21 25 PM" src="https://github.com/Deep-MI/FastSurfer/assets/36212932/cbd06501-4eaf-4d4f-95c0-047d498b5614">

**Comment by dkuegler** [comment] 2024-04-20 11:21
If you are just using FastSurfer via `run_fastsurfer.sh` or `run_prediction.py`, you will not get results as defined by `config/config/FastSurfer_ColorLUT.tsv`.
Only [Inference.eval](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.inference.html#FastSurferCNN.inference.Inference.eval) (and [Inference.run](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.inference.html#FastSurferCNN.inference.Inference.run)) has the segmentations as defined by `config/FastSurfer_ColorCUT.tsv` ... this is mapped to the label space used by FreeSurfer in [RunModelOnData.get_prediction](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.run_prediction.html#FastSurferCNN.run_prediction.RunModelOnData.get_prediction):

https://github.com/Deep-MI/FastSurfer/blob/16335a9db7be4bb5190be3f57de252266ef3f2e0/FastSurferCNN/run_prediction.py#L398-L413

I am not really sure what you are really comparing right now; FreeSurfer segmentation with FastSurfer's `aparc+DKTatlas.aseg.deep.mgz` ?

It seems to me you are manually calling just [Inference.run](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.inference.html#FastSurferCNN.inference.Inference.run) and skipping the post processing steps in [RunModelOnData.get_prediction](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.run_prediction.html#FastSurferCNN.run_prediction.RunModelOnData.get_prediction).

**Comment by dkuegler** [comment] 2024-04-20 11:32
Also, I am not sure about which metrics you are using in your plots? Is this correlation of volumes?

Those numbers look awfully low... And with comparisons between FreeSurfer and FastSurfer it will always be difficult to say what is better if you compare them with respect to each other. Furthermore, cortical regions evaluated on the volume can always be very misleading.

All that said, we run per-release continuous validation of FastSurfer and make sure the metrics presented in both the FastSurfer and the FastSurferVINN paper are still satisfied. Specifically, this means Test-Retest metrics such as https://www.sciencedirect.com/science/article/pii/S1053811920304985#fig9 and Dice evaluations.

**Comment by m-reuter** [comment] 2024-04-20 20:04
Yes, if you want to compare volumes for the structures, use the values in aseg.stats or aparc+aseg.stats after a full run of FastSurfer (including the surface module), as we correct some volumes with the surfaces similar to FreeSurfer.

**Comment by gmeng92** [comment] 2024-04-21 18:03
> If you are just using FastSurfer via `run_fastsurfer.sh` or `run_prediction.py`, you will not get results as defined by `config/config/FastSurfer_ColorLUT.tsv`. Only [Inference.eval](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.inference.html#FastSurferCNN.inference.Inference.eval) (and [Inference.run](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.inference.html#FastSurferCNN.inference.Inference.run)) has the segmentations as defined by `config/FastSurfer_ColorCUT.tsv` ... this is mapped to the label space used by FreeSurfer in [RunModelOnData.get_prediction](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.run_prediction.html#FastSurferCNN.run_prediction.RunModelOnData.get_prediction):
> 
> https://github.com/Deep-MI/FastSurfer/blob/16335a9db7be4bb5190be3f57de252266ef3f2e0/FastSurferCNN/run_prediction.py#L398-L413
> 
> I am not really sure what you are really comparing right now; FreeSurfer segmentation with FastSurfer's `aparc+DKTatlas.aseg.deep.mgz` ?
> 
> It seems to me you are manually calling just [Inference.run](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.inference.html#FastSurferCNN.inference.Inference.run) and skipping the post processing steps in [RunModelOnData.get_prediction](https://deep-mi.org/FastSurfer/dev/api/generated/FastSurferCNN.run_prediction.html#FastSurferCNN.run_prediction.RunModelOnData.get_prediction).

Yes. Exactly. The results I showed are after running the` run_prediction.py.` only, and the comparison I performed is between the FreeSurfer output: `aparc.DKTatlas+aseg.mgz` and the FastSurfer output: `aparc+DKTatlas.aseg.deep.mgz`. I used the correlation to compare the consistence for each ROI.  So I am pretty sure the problem is due to the skipping of the Postprocessing step you mentioned. And as m-reuter commented(https://github.com/Deep-MI/FastSurfer/issues/514#issuecomment-2067769322), I should make a full run of FastSurfer including the surface module. Thanks for both of your detailed explanations!

**Comment by dkuegler** [comment] 2024-04-22 13:29
Even `run_prediction.py` should output valid segmentation files, so I guess I still don't quite understand what you mean, but I would recommend using `run_fastsurfer.sh --seg_only` if you wanted to run FastSurfer without the surface pipeline anyway...

**Comment by gmeng92** [comment] 2024-04-22 14:15
Well. I expected two things : the segmented image and the volume stats corresponding to the segmentation. In the earlier post, all the results were collected after I run the `run_prediction.py`. And the volumes stats is calculated based on the  `aparc+DKTatlas.aseg.deep.mgz`. As you and [m-reuter](https://github.com/m-reuter) mentioned, you have a separated Post-processing step for the volumes estimation. I should use the values in `aseg.stats` or `aparc+aseg.stats`.  The volumes stats should then comparable to the FreeSurfer estimated. Am I understanding it right?

**Comment by dkuegler** [comment] 2024-04-22 14:49
That all sounds correct, the only thing that does not match up is that the statistics you presented up top make no sense as an output to `run_prediction.py`. The postprocessing is built into `run_prediction.py`. The error that you are presenting makes no sense to me.
You should also use [FreeSurferColorLUT.txt](https://github.com/Deep-MI/FastSurfer/blob/dev/FastSurferCNN/config/FreeSurferColorLUT.txt) with the `aparc.DKTatlas+aseg.deep.mgz` to identify different labels (which is the same as FreeSurfer).

To achieve this, we recommend running fastsurfer with the `run_fastsurfer.sh` (`--seg_only` or not) to get the `aseg.mgz`or `aparc.DKTatlas+aseg.*****.mgz`. They should all have all labels (left and right) and should be complete. We NEVER save the data before applying the postprocessing steps in FastSurfer. This way your reported
> And all those mismatches happen to be on the right hemisphere cortex.

Makes no sense to me, I have never seen this issue and I cannot reproduce this.
I guess if it works fine for you now, we can close this issue, but if you have a file that has missing labels, please give us a short script that reproduces this. This should never happen.

**Comment by gmeng92** [comment] 2024-04-25 16:31
The example I was using is from the Tutorial Notebook (https://github.com/Deep-MI/FastSurfer/blob/dev/Tutorial/Complete_FastSurfer_Tutorial.ipynb). `!curl -k https://surfer.nmr.mgh.harvard.edu/pub/data/tutorial_data/buckner_data/tutorial_subjs/140/mri/orig.mgz -o "{SETUP_DIR}140_orig.mgz"
`. I run both the FastSurfer and FreeSurfer to compare the segmented images between `aparc.DKTatlas+aseg.deep.mgz` (FastSurfer) and `aparc.DKTatlas+aseg.mgz` (FreeSurfer). Here are the scripts I ran to generate the resulted images:

1. FastSurfer:
- run_prediction.py : `input_dir=/Users/Projects/naip_data/Example_image
output_dir=/Users/Projects/naip_data/Example_image/FastSurfer_result_run_fastsurfer
python3 run_prediction.py --t1 $input_dir/subject_140/example140_orig.mgz \
         --asegdkt_segfile $output_dir/subject_140/aparc.DKTatlas+aseg.deep.mgz \
          --conformed_name $output_dir/subject_140/subconformed.mgz \
          --brainmask_name $output_dir/subject_140/mri/mask.mgz \
          --aseg_name $output_dir/subject_140/mri/aseg.auto_noCCseg.mgz \
          --sid subject_140 \
          --seg_log $output_dir/subject_140/scripts/deep-seg.log \
          --vox_size min \
          --batch_size 1`
- N4_bias_correct.py `python3 N4_bias_correct.py --in $output_dir/subject_140/subconformed.mgz \
                           --out $output_dir/subject_140/mri/corrected.mgz \
                           --rescale $output_dir/subject_140/mri/rescaled.mgz \
                           --aseg $output_dir/subject_140/aparc.DKTatlas+aseg.deep.mgz \
                           --threads 4`
- segstats.py: `fastsurfercnndir=/Users/Projects/FastSurfer/FastSurferCNN
output_dir=/Users/Projects/naip_data/Example_image/FastSurfer_result_run_fastsurfer
python3 segstats.py --segfile $output_dir/subject_140/aparc.DKTatlas+aseg.deep.mgz \
                    --segstatsfile $output_dir/subject_140/segs.stats \
                    --normfile $output_dir/subject_140/mri/corrected.mgz \
                    --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 \
                    --lut $fastsurfercnndir/config/FreeSurferColorLUT.txt \
                    --empty \
                    --threads 4`
2. FreeSurfer:

- recon-all `export SUBJECTS_DIR="/Users/Projects/naip_data/Example_image/FreeSurfer_result"
recon-all -i subject_140/example140_orig.mgz \
        -s "subject_140" \
        -all \
        -parallel \
        -openmp 8`

All the codes are run on a MacBookPro with M1 Max chip, current OS version is 14.4.1 (macOS Sonoma). The FasterSurfer version is the latest Stable branch `https://github.com/Deep-MI/FastSurfer/tree/stable`; the FreeSurfer Version is 7.4.1. 

By checking the segmented images, I have noticed that six cortex regions are missing from the `aparc.DKTatlas+aseg.deep.mgz`, which can also be found in the `sets.stats` file
<img width="685" alt="Screenshot 2024-04-25 at 11 23 52 AM" src="https://github.com/Deep-MI/FastSurfer/assets/36212932/b55797a4-002e-4885-b6bf-e01bea22693f">
I also visually compared them using Freeview
<img width="1307" alt="Screenshot 2024-04-25 at 11 26 40 AM" src="https://github.com/Deep-MI/FastSurfer/assets/36212932/5e1be614-cb7a-4d3b-988e-f7ce8b0aaa0a">
So you can see that large `2028 ctx-rh_superiorfrontal` region is mislabeled as the `2016 cox-rh-parapippocampal` in `aparc.DKTatlas+aseg.deep.mgz`.

**Comment by dkuegler** [comment] 2024-04-25 17:22
First off, thank you for the detailed report.
We will try to recreate the issue you presented here.

**Comment by m-reuter** [comment] 2024-04-25 17:53
Have you tried running FastSurfer (i) with run_fastsurfer --seg only and ii) the full pipeline ? I would not expect missing regions in either of those two options. I think that the problem comes from something you are doing differently from how FastSurfer does it.

**Comment by gmeng92** [comment] 2024-04-25 20:15
> Have you tried running FastSurfer (i) with run_fastsurfer --seg only and ii) the full pipeline ? I would not expect missing regions in either of those two options. I think that the problem comes from something you are doing differently from how FastSurfer does it.

Yep. I tried the `run_fastsurfer --seg only` option but it keeps throwing out the syntax error.. But It should not make differences because this option basically runs the identically 3 steps as I mentioned. I also confirmed that I run with the same parameters as in `run_fastsurfer.sh` line 645-687

**Comment by m-reuter** [comment] 2024-04-25 20:21
You are using the latest release version, right? And a native install or inside Docker?
Our release (at least in docker) does not throw any syntax errors. That means that something is not setup correctly on your system and that may cause all kinds of problems.

**Comment by gmeng92** [comment] 2024-04-25 20:38
I used the latest release version and the native install.  Besides that, I also tried to run the same python scripts in a GCP VM and the results are consistent with that on my MacPro.  I will also re-setup and try the `run_fastsurfer.sh` script and get back to you once I figure it out.

**Comment by gmeng92** [comment] 2024-04-25 21:12
FYI. Thanks for your patience and response.  I reset-up the native install and rerun the `run_fastsurfer.sh` by using 

`export PYTORCH_ENABLE_MPS_FALLBACK=1
input_dir=/Users/Projects/naip_data/Example_image
output_dir=/Users/Projects/naip_data/Example_image/sh_run
bash ./run_fastsurfer.sh  --seg_only --t1 $input_dir/subject_140/example140_orig.mgz \
         --sd $output_dir \
          --sid subject_140 \
          --seg_log $output_dir/subject_140/scripts/deep-seg.log \
          --vox_size min`

And the resulted `aseg+DKT.stats` indicates the same problem on the right hemisphere:
- Here is the stats file 
``` # Title Segmentation Statistics
#
# generating_program segstats.py
# cmdline /Users/Projects/FastSurfer/FastSurferCNN/segstats.py --segfile /Users/Projects/naip_data/Example_image/sh_run/subject_140/mri/aparc.DKTatlas+aseg.deep.mgz --segstatsfile /Users/Projects/naip_data/Example_image/sh_run/subject_140/stats/aseg+DKT.stats --normfile /Users/Projects/naip_data/Example_image/sh_run/subject_140/mri/orig_nu.mgz --empty --excludeid 0 --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 --lut /Users/Projects/FastSurfer/FastSurferCNN/config/FreeSurferColorLUT.txt --threads 1
# sysname  Darwin
# hostname R5332690
# machine  arm64
# user       **
# anatomy_type volume
#
# SegVolFile /Users/Projects/naip_data/Example_image/sh_run/subject_140/mri/aparc.DKTatlas+aseg.deep.mgz
# SegVolFileTimestamp 2024/04/25 16:00:20
# ColorTable /Users/Projects/FastSurfer/FastSurferCNN/config/FreeSurferColorLUT.txt
# ColorTableTimestamp 2023/11/28 12:41:37
# PVVolFile /Users/Projects/naip_data/Example_image/sh_run/subject_140/mri/orig_nu.mgz
# PVVolFileTimestamp 2024/04/25 16:01:29
# Excluding Unknown
# ExcludeSegId 0
# compatibility with freesurfer's mri_segstats: fixed
#
# Only reporting non-empty segmentations
# VoxelVolume_mm3 1.0
# TableCol  1 ColHeader Index
# TableCol  1 FieldName Index
# TableCol  1 Units     NA
# TableCol  2 ColHeader SegId
# TableCol  2 FieldName Segmentation Id
# TableCol  2 Units     NA
# TableCol  3 ColHeader NVoxels
# TableCol  3 FieldName Number of Voxels
# TableCol  3 Units     NA
# TableCol  4 ColHeader Volume_mm3
# TableCol  4 FieldName Volume
# TableCol  4 Units     mm^3
# TableCol  5 ColHeader StructName
# TableCol  5 FieldName Structure Name
# TableCol  5 Units     NA
# TableCol  6 ColHeader normMean
# TableCol  6 FieldName Intensity normMean
# TableCol  6 Units     MR
# TableCol  7 ColHeader normStdDev
# TableCol  7 FieldName Intensity normStdDev
# TableCol  7 Units     MR
# TableCol  8 ColHeader normMin
# TableCol  8 FieldName Intensity normMin
# TableCol  8 Units     MR
# TableCol  9 ColHeader normMax
# TableCol  9 FieldName Intensity normMax
# TableCol  9 Units     MR
# TableCol  10 ColHeader normRange
# TableCol  10 FieldName Intensity normRange
# TableCol  10 Units     MR
# NRows 100
# NTableCols 10
# ColHeaders  Index SegId NVoxels Volume_mm3 StructName normMean normStdDev normMin normMax normRange
 1    2 235812 237746.116 Left-Cerebral-White-Matter      104.4247 10.3612 32.0000 159.0000 127.0000
 2    4   4545   4952.761 Left-Lateral-Ventricle           32.9030 13.4104  8.0000  83.0000  75.0000
 3    5    346    387.378 Left-Inf-Lat-Vent                45.4971 15.3537 13.0000  78.0000  65.0000
 4    7  13783  14494.498 Left-Cerebellum-White-Matter     88.2693  7.7376 43.0000 115.0000  72.0000
 5    8  59743  58270.368 Left-Cerebellum-Cortex           59.3271 10.8519 11.0000 100.0000  89.0000
 6   10   7849   7612.716 Left-Thalamus                    87.7969 11.5315 49.0000 151.0000 102.0000
 7   11   3709   3644.872 Left-Caudate                     73.1833  9.1688 46.0000 100.0000  54.0000
 8   12   5621   5598.155 Left-Putamen                     83.0101  8.8305 37.0000 107.0000  70.0000
 9   13   2038   1974.462 Left-Pallidum                   100.0918  5.7893 62.0000 120.0000  58.0000
10   14    790    906.554 3rd-Ventricle                    44.7544 12.5743 11.0000  71.0000  60.0000
11   15   1642   1730.551 4th-Ventricle                    27.7838 11.4900  9.0000  65.0000  56.0000
12   16  20173  20247.048 Brain-Stem                       84.2705 10.5840 23.0000 146.0000 123.0000
13   17   4152   4149.399 Left-Hippocampus                 64.3032  9.4892 18.0000 105.0000  87.0000
14   18   1636   1617.073 Left-Amygdala                    63.7207  7.6648 42.0000  92.0000  50.0000
15   24   1018   1097.971 CSF                              38.4597 13.9851  8.0000  82.0000  74.0000
16   26    737    733.083 Left-Accumbens-area              67.2510  5.7725 47.0000  88.0000  41.0000
17   28   4329   4208.293 Left-VentralDC                   95.2624 13.1812 45.0000 195.0000 150.0000
18   31    696    635.700 Left-choroid-plexus              60.9195 13.2763 30.0000  91.0000  61.0000
19   41 240047 242007.951 Right-Cerebral-White-Matter     104.5752 10.0847 23.0000 165.0000 142.0000
20   43   4070   4466.071 Right-Lateral-Ventricle          33.2533 13.4157  7.0000  72.0000  65.0000
21   44    288    324.597 Right-Inf-Lat-Vent               40.2604 12.4908 10.0000  75.0000  65.0000
22   46  13111  13814.726 Right-Cerebellum-White-Matter    89.0185  7.5143 47.0000 116.0000  69.0000
23   47  58315  56810.969 Right-Cerebellum-Cortex          59.4391 11.3248 11.0000 104.0000  93.0000
24   49   7571   7258.268 Right-Thalamus                   87.2058 11.2463 39.0000 129.0000  90.0000
25   50   3970   3898.052 Right-Caudate                    72.6441  9.1387 44.0000  99.0000  55.0000
26   51   5657   5666.730 Right-Putamen                    83.0108  8.2736 45.0000 106.0000  61.0000
27   52   2221   2150.047 Right-Pallidum                  100.5016  5.7306 64.0000 122.0000  58.0000
28   53   4464   4440.940 Right-Hippocampus                64.3273 10.7075 14.0000 118.0000 104.0000
29   54   1955   1920.577 Right-Amygdala                   65.6005  7.4470 33.0000  90.0000  57.0000
30   58    669    655.138 Right-Accumbens-area             68.6084  6.7208 50.0000  91.0000  41.0000
31   60   4187   4056.925 Right-VentralDC                  95.2087 14.5583 45.0000 222.0000 177.0000
32   63    916    863.962 Right-choroid-plexus             59.5721 12.6675 23.0000  95.0000  72.0000
33   77   1361   1143.894 WM-hypointensities               74.8935 11.3578 43.0000 102.0000  59.0000
34  251      0      0.000 CC_Posterior                      0.0000  0.0000  0.0000   0.0000   0.0000
35  252      0      0.000 CC_Mid_Posterior                  0.0000  0.0000  0.0000   0.0000   0.0000
36  253      0      0.000 CC_Central                        0.0000  0.0000  0.0000   0.0000   0.0000
37  254      0      0.000 CC_Mid_Anterior                   0.0000  0.0000  0.0000   0.0000   0.0000
38  255      0      0.000 CC_Anterior                       0.0000  0.0000  0.0000   0.0000   0.0000
39 1002   3621   3452.435 ctx-lh-caudalanteriorcingulate   63.7929  8.8705 42.0000  94.0000  52.0000
40 1003   7311   6755.580 ctx-lh-caudalmiddlefrontal       66.1284  9.5127 37.0000  92.0000  55.0000
41 1005   4543   4137.500 ctx-lh-cuneus                    69.0980  9.8173 43.0000  97.0000  54.0000
42 1006   2238   2102.425 ctx-lh-entorhinal                57.1912  7.3592 37.0000  83.0000  46.0000
43 1007   9674   8852.001 ctx-lh-fusiform                  62.3423  8.8841 32.0000 118.0000  86.0000
44 1008  12843  11941.699 ctx-lh-inferiorparietal          66.6714  8.8835 40.0000 101.0000  61.0000
45 1009  12979  12348.884 ctx-lh-inferiortemporal          59.6272  9.3604 33.0000  93.0000  60.0000
46 1010   2771   2591.406 ctx-lh-isthmuscingulate          65.7333  9.7160 40.0000 107.0000  67.0000
47 1011  13809  12690.389 ctx-lh-lateraloccipital          66.9920  9.7476 34.0000  96.0000  62.0000
48 1012   9098   8698.988 ctx-lh-lateralorbitofrontal      59.5398  9.0423 34.0000 109.0000  75.0000
49 1013   7574   6953.548 ctx-lh-lingual                   65.4802  9.3684 34.0000 105.0000  71.0000
50 1014   4949   4722.012 ctx-lh-medialorbitofrontal       59.7201  8.8491 36.0000  91.0000  55.0000
51 1015  17249  16304.374 ctx-lh-middletemporal            61.5557  8.9049 30.0000  99.0000  69.0000
52 1016   2607   2429.966 ctx-lh-parahippocampal           60.3483  9.2009 33.0000 114.0000  81.0000
53 1017   5149   4749.311 ctx-lh-paracentral               67.9077 10.4244 41.0000  93.0000  52.0000
54 1018   4345   3996.607 ctx-lh-parsopercularis           63.8603  8.9154 37.0000 109.0000  72.0000
55 1019   2540   2347.442 ctx-lh-parsorbitalis             60.3008  8.0496 36.0000  92.0000  56.0000
56 1020   3416   3085.499 ctx-lh-parstriangularis          65.0498  9.2129 40.0000  91.0000  51.0000
57 1021   2122   1945.103 ctx-lh-pericalcarine             71.0156  9.9949 45.0000  99.0000  54.0000
58 1022  13348  12223.926 ctx-lh-postcentral               68.5264 10.2093 35.0000  97.0000  62.0000
59 1023   4384   4209.302 ctx-lh-posteriorcingulate        64.9726  8.6383 39.0000 104.0000  65.0000
60 1024  16287  14983.607 ctx-lh-precentral                68.6454 10.5879 35.0000 111.0000  76.0000
61 1025  11111  10589.550 ctx-lh-precuneus                 65.2330  8.9569 40.0000 106.0000  66.0000
62 1026   3153   2965.030 ctx-lh-rostralanteriorcingulate  61.0704  8.2731 39.0000 110.0000  71.0000
63 1027  11607  10930.631 ctx-lh-rostralmiddlefrontal      63.7181  8.7911 38.0000  91.0000  53.0000
64 1028  27691  26582.907 ctx-lh-superiorfrontal           63.5407  8.8792 37.0000 107.0000  70.0000
65 1029   9662   9082.893 ctx-lh-superiorparietal          67.9797  9.6189 41.0000  94.0000  53.0000
66 1030  19656  18293.513 ctx-lh-superiortemporal          62.9718 10.2848 33.0000 139.0000 106.0000
67 1031  13096  12425.588 ctx-lh-supramarginal             66.7676  9.0792 34.0000 106.0000  72.0000
68 1034   1524   1314.625 ctx-lh-transversetemporal        73.1791 11.8291 36.0000 161.0000 125.0000
69 1035   6513   6337.730 ctx-lh-insula                    62.9702  8.7621 41.0000 127.0000  86.0000
70 2002   2935   2818.420 ctx-rh-caudalanteriorcingulate   62.8777  7.9327 41.0000  90.0000  49.0000
71 2003  11392  10472.983 ctx-rh-caudalmiddlefrontal       67.0565  9.5292 40.0000  99.0000  59.0000
72 2005   2921   2715.745 ctx-rh-cuneus                    65.8946  9.5893 41.0000 109.0000  68.0000
73 2006  11590  11009.112 ctx-rh-entorhinal                61.7133  8.9655 36.0000 103.0000  67.0000
74 2007  17878  16652.963 ctx-rh-fusiform                  63.9814  9.6706 32.0000 117.0000  85.0000
75 2008  20552  19102.116 ctx-rh-inferiorparietal          64.8971  9.1914 34.0000 128.0000  94.0000
76 2009  17347  16384.406 ctx-rh-inferiortemporal          59.4172  9.1259 29.0000 115.0000  86.0000
77 2010   4322   3980.587 ctx-rh-isthmuscingulate          68.9155 10.2331 40.0000  95.0000  55.0000
78 2011  14105  12882.462 ctx-rh-lateraloccipital          70.4138 10.5267 40.0000 100.0000  60.0000
79 2012  12073  11036.849 ctx-rh-lateralorbitofrontal      68.6554 10.0430 37.0000  99.0000  62.0000
80 2013   4437   4246.702 ctx-rh-lingual                   65.4607  8.9369 45.0000  93.0000  48.0000
81 2014  15280  13968.321 ctx-rh-medialorbitofrontal       68.4794 10.6059 37.0000  97.0000  60.0000
82 2015  27200  25482.907 ctx-rh-middletemporal            63.8432  8.9673 35.0000 103.0000  68.0000
83 2016  29443  28467.873 ctx-rh-parahippocampal           63.7325  8.8039 38.0000  96.0000  58.0000
84 2017      0      0.000 ctx-rh-paracentral                0.0000  0.0000  0.0000   0.0000   0.0000
85 2018   5466   5052.973 ctx-rh-parsopercularis           63.4837  8.6804 32.0000  95.0000  63.0000
86 2019   2636   2422.436 ctx-rh-parsorbitalis             61.6278  8.2544 40.0000 100.0000  60.0000
87 2020   3815   3458.211 ctx-rh-parstriangularis          64.3387  8.8251 40.0000  92.0000  52.0000
88 2021      0      0.000 ctx-rh-pericalcarine              0.0000  0.0000  0.0000   0.0000   0.0000
89 2022      0      0.000 ctx-rh-postcentral                0.0000  0.0000  0.0000   0.0000   0.0000
90 2023      0      0.000 ctx-rh-posteriorcingulate         0.0000  0.0000  0.0000   0.0000   0.0000
91 2024      0      0.000 ctx-rh-precentral                 0.0000  0.0000  0.0000   0.0000   0.0000
92 2025      0      0.000 ctx-rh-precuneus                  0.0000  0.0000  0.0000   0.0000   0.0000
93 2026   2431   2266.472 ctx-rh-rostralanteriorcingulate  61.4155  8.1383 40.0000  97.0000  57.0000
94 2027  11237  10610.506 ctx-rh-rostralmiddlefrontal      64.2210  8.6774 38.0000  92.0000  54.0000
95 2028      0      0.000 ctx-rh-superiorfrontal            0.0000  0.0000  0.0000   0.0000   0.0000
96 2029  10876  10018.971 ctx-rh-superiorparietal          68.6001  9.9246 35.0000 101.0000  66.0000
97 2030  17784  16483.333 ctx-rh-superiortemporal          62.5459  9.9819 35.0000 118.0000  83.0000
98 2031  14486  13629.394 ctx-rh-supramarginal             66.8300  9.0767 40.0000 114.0000  74.0000
99 2034   1063    936.825 ctx-rh-transversetemporal        70.6115 10.8854 30.0000 116.0000  86.0000
100 2035   6240   6132.294 ctx-rh-insula                    62.4325  7.9858 41.0000  94.0000  53.0000
```
I covered my Username due to private concern. But that wouldn't affect the result.

**Comment by zainthecoder** [comment] 2024-04-30 16:22
I'm unable to reproduce the issue. 
Could you please create a **Docker or Singularity container** and try running the run_fastsurfer.sh script there? 

In the meantime, could you share the deep-seg.log file here?

**Comment by gmeng92** [comment] 2024-04-30 16:42
[deep-seg.log](https://github.com/Deep-MI/FastSurfer/files/15168142/deep-seg.log)
Here is the log file. I initially tried the Docker container but couldn't get it running there(see my previous post https://github.com/Deep-MI/FastSurfer/issues/379). That is why I used the native install and started from there. I will also keep debugging this issue. By the way, can you also share the log file as well? Appreciate for the response and help.

**Comment by zainthecoder** [comment] 2024-05-07 09:45
Yes, Sure.
Sharing my log file.
[deep-seg.log](https://github.com/Deep-MI/FastSurfer/files/15233646/deep-seg.log)

**Comment by m-reuter** [comment] 2024-06-03 10:56
@zainthecoder Note that this seems to be a native install on a modern Mac Book (with M chip). 
We need to try to replicate this on a similar Mac. Also note that #379 shows that docker does not work as expected on those Mac books (the reason is the ARM chips and our intel docker images will be very slow, as they also cannot use the GPU, but only CPU and need emulation). Which is why native install makes sense on the M-Chip Macs. It worked for me a while ago, and I could even make use of the GPU acceleration (segmentation in 2 minutes), but not sure about the more recent FastSurfer versions.

**Comment by m-reuter** [comment] 2024-06-19 20:18
@gmeng92 I just merged #530 into the dev branch. This will make it easier to install and run FastSurfer on your M1 Mac. The only caveat is that the dev version of FastSurfer is not tested. But you could give it a try. 

Also in order to replicate your results we would need your image and run it on a Mac and Linux. We do not expect regions to be missing and it indicates either a problem in the way you run it or a problem with the quality of the image (or simply out-of-distribution).

**Comment by m-reuter** [comment] 2024-06-20 06:17
You could also try to run your setup on one of the tutorial images:
```
curl -k https://surfer.nmr.mgh.harvard.edu/pub/data/tutorial_data/buckner_data/tutorial_subjs/140/mri/orig.mgz -o "140_orig.mgz"
```
If it gives the same missing regions, it is your setup that has issues. If not, it is your image.

**Comment by m-reuter** [comment] 2024-07-02 08:29
Closing this for now due to inactivity and could not replicate.

**Closed as completed by m-reuter** 2024-07-02 08:29 UTC
Labels: question, needs-repro
