### ISSUE TITLE
Cannot use Fastsurfer with Apple M3 Pro

### ISSUE THREAD

**Issue by HaotingWu** [Deep-MI/FastSurfer#551] opened 2024-08-03 10:28 UTC
I installed FastSurfer natively on a Mac with an Apple M3 Pro, and encountered the following errors when using run_fastsurfer.sh:

<img width="968" alt="截屏2024-08-03 18 25 52" src="https://github.com/user-attachments/assets/e84c40c5-b6c9-4366-b0cc-8db7784136ea">

**Comment by dkuegler** [comment] 2024-08-05 16:30
Hi the issue here is, that your [bash version is outdated](https://github.com/Deep-MI/FastSurfer/blob/dev/doc/overview/INSTALL.md#1-dependency-packages).

Please update bash.

Please note, that we have changed the code so that future releases will be compatible with earlier versions of bash.

**Comment by m-reuter** [comment] 2024-08-07 21:37
See also issue #528 , you may need to modify the bash shebang #! (first line ) in all bash scripts so that they actually use the manually installed bash version (which you can get e.g. via home brew). Or you can just try the dev version which we will release pretty soon.

**Comment by HaotingWu** [comment] 2024-08-08 06:25
Following your recommendation, I updated Bash to version 5.2.3, but it still isn't working
![Uploading 截屏2024-08-08 14.20.57.png…]()

**Comment by HaotingWu** [comment] 2024-08-08 06:30
Following your recommendation, I updated Bash to version 5.2.3, but it still isn't working
<img width="851" alt="截屏2024-08-08 14 20 57" src="https://github.com/user-attachments/assets/29b2842d-3c65-463d-bbf4-3b1b9f57603d">

**Comment by m-reuter** [comment] 2024-08-08 08:06
Did you update all the first lines in all bash scripts (with ending .sh) like recommended here: https://github.com/Deep-MI/FastSurfer/issues/528#issuecomment-2176149055
otherwise it will internally still use the old bash version from the system rather than the new one. 

What version of FastSurfer exactly are you using anyway?

**Comment by HaotingWu** [comment] 2024-08-08 12:04
Hi ! Thanks for your quick reply. I have already used Bash 5.2 to run the commands, but I'm still encountering the same issue.

**Comment by m-reuter** [comment] 2024-08-08 13:37
Can you answer the questions to help us debug this:
- what exact FastSurfer version are you using?  Run: ```bash run_fastsurfer.sh --version``` , and what is written in pyproject.toml under version ?
- how did you install bash , probably via homebrew?

And what I said in my posts above: it is not sufficient to install a newer bash in addition to the system bash. The problem is that the script will still use the system bash. This is because in each bash script the first line says: ```#!/bin/bash```which points it to the system version. So you need to search for this string in all files and replace it with ```#!/usr/bin/env bash``` . You can also download our dev branch where it should work already.

**Comment by HaotingWu** [comment] 2024-08-08 14:24
Hi, the version I used was 2.2.0+818acf1, and the version of Bash was installed via Homebrew. I have changed the first line and ran FastSurfer again, but a new issue occurred.

**Comment by m-reuter** [comment] 2024-08-08 21:17
Please post the new error (I cannot see any attached images here). 
Also (see above) you need to replace this string in **all** files.

**Comment by HaotingWu** [comment] 2024-08-10 08:45
Hi, I've made the changes you suggested by updating all occurrences of 'bin/bash' to 'opt/homebrew/bin/bash'. Similarly, I updated 'bin/python3' to 'opt/homebrew/bin/python3'. However, I’ve encountered a new issue.When I run FastSurfer, I get the following error:
    File "/Users/wuhaoting/Fastsurfer/FastSurferCNN/run_prediction.py", line 23, in     import numpy as npModuleNotFoundError: No module named ‘numpy’
        
    I then checked the Python environment and found that numpy is located at /Users/wuhaoting/python-envs/fastsurfer/lib/python3.10/site-packages/numpy.

**Comment by m-reuter** [comment] 2024-08-11 10:59
Hi, our install notes https://deep-mi.org/FastSurfer/overview/INSTALL.html#macos 
describe how to setup an install the python dependencies in a separate environment.

**Comment by dkuegler** [comment] 2024-08-11 14:49
> Hi, I've made the changes you suggested by updating all occurrences of 'bin/bash' to 'opt/homebrew/bin/bash'. Similarly, I updated 'bin/python3' to 'opt/homebrew/bin/python3'. However, I’ve encountered a new issue.When I run FastSurfer, I get the following error: File "/Users/wuhaoting/Fastsurfer/FastSurferCNN/run_prediction.py", line 23, in     import numpy as npModuleNotFoundError: No module named ‘numpy’ I then checked the Python environment and found that numpy is located at /Users/wuhaoting/python-envs/fastsurfer/lib/python3.10/site-packages/numpy.

This means your installation does not have numpy installed. Which makes sense, because your python is now the python in `/Users/wuhaoting/python-envs/fastsurfer` and not `opt/homebrew/bin/python3`.

At this point I would suggest you try waiting until the next version is released or switching to the dev-version of FastSurfer (the latter should probably only be used for testing as this is not a proper release).

**Comment by m-reuter** [comment] 2024-08-30 10:17
Our updates in #530 and #561 should fix the problems with bash. They will be part of our upcoming release, feel free to re-open if the same issues still occur.

**Closed as completed by m-reuter** 2024-08-30 10:17 UTC
