### ISSUE TITLE
ipynb tutorial: "Run Interact" is not working. While clicking the button only white space is displayed.

### ISSUE THREAD

**Issue by shijinknox007** [Deep-MI/FastSurfer#280] opened 2023-03-23 08:15 UTC
Hi all,

I am trying to execute Complete_FastSurfer_Tutorial.ipynb in colab. Then I came across with some issues.

1. I am using "Alternative" option to upload the input image (tutorial image)
2. Run fastsurfer
3. Plot some slices from the segmented brain - then I got an error "ValueError: keyword grid_b is not recognized" (but Slices, Prediction, and Overlay_GT images were displayed)
4. Upon clicking "Run Interact" - Nothing is displaying but a white space

Thanks and Regards,
Shijin Knox G.U

**Comment by LeHenschel** [comment] 2023-03-23 11:58
The Value Error appears because the first parameter of Axes.grid and Axis.grid has been renamed to visible (was previously named b). Can be fixed changing ax.grid(b=None) to ax.grid(visible=None) in the corresponding function for slice plotting. The new matplotlib version might also cause the bug of not correctly displaying the figure for the mesh plot. @agirodi @AhmedFaisal95 please have a look.

**Comment by agirodi** [comment] 2023-03-27 12:12
The ValueError was fixed by `b=None` to `visible=None`.

For the second error, I can only say that matplotlib is not the cause of the error. It neither seems to be used in that code cell nor did downgrading the matplotlib to the previous version fixes the error. I tried downgrading some other packages, even forcing the entire Fastsurfer dependencies versions, to no result.
According to the [release notes](https://colab.research.google.com/notebooks/relnotes.ipynb), these are the changed packages we use, since the last NB update (as far as I can tell). Its probably one of those:

> absl-py
> cachetools
> charset-normalizer
> importlib-metadata
> matplotlib
> networkx
> numpy
> packaging
> pandas
> pillow
> protobuf
> requests
> scikit-image
> scikit-learn
> scipy
> tenacity
> tensorboard
> tifffile
> torch
> torchvision
> typing-extensions
> urllib3
> werkzeug
> wrapt
> zipp

I can look into which one exactly does the error, by downgrading each. But maybe someone can already see where the problem may lie.

**Comment by shijinknox007** [comment] 2023-03-28 05:31
> The ValueError was fixed by `b=None` to `visible=None`.
> 
> For the second error, I can only say that matplotlib is not the cause of the error. It neither seems to be used in that code cell nor did downgrading the matplotlib to the previous version fixes the error. I tried downgrading some other packages, even forcing the entire Fastsurfer dependencies versions, to no result. According to the [release notes](https://colab.research.google.com/notebooks/relnotes.ipynb), these are the changed packages we use, since the last NB update (as far as I can tell). Its probably one of those:
> 
> > absl-py
> > cachetools
> > charset-normalizer
> > importlib-metadata
> > matplotlib
> > networkx
> > numpy
> > packaging
> > pandas
> > pillow
> > protobuf
> > requests
> > scikit-image
> > scikit-learn
> > scipy
> > tenacity
> > tensorboard
> > tifffile
> > torch
> > torchvision
> > typing-extensions
> > urllib3
> > werkzeug
> > wrapt
> > zipp
> 
> I can look into which one exactly does the error, by downgrading each. But maybe someone can already see where the problem may lie.

OK..... :(

**Comment by af-a** [comment] 2023-04-03 15:01
I have not interacted with these tutorials before, but I had quick look and was able to reproduce the problem but could not find a version of the notebook (in the history) in which this did not happen.
If anyone can provide a version of the notebook that worked in the past, it could be helpful in diagnosing the issue.

**Comment by LeHenschel** [comment] 2023-04-03 15:05
The first version definitely worked. This might also be an issue with colab and not the code or the dependencies. I would be helpful, if one of you could determine if the issue also persists in a jupyter notebook.

EDIT: This seems indeed to be an issue with colab as the code is working fine in jupyter notebook (see below). I also attached the pip freeze output.

![Screenshot from 2023-04-03 17-14-33](https://user-images.githubusercontent.com/31760921/229553209-c0a9470f-f328-4b57-8b29-f32e86ba2949.png)
[pip_freeze_ipyplot.txt](https://github.com/Deep-MI/FastSurfer/files/11139752/pip_freeze_ipyplot.txt)

**Comment by af-a** [comment] 2023-04-03 15:27
So it's either a problem specific to colab or a possibly a dependency whose version in the colab notebook is problematic but is ok in the env you shared.

Here's the same from the colab notebook: 
[pip_freeze_colab.txt](https://github.com/Deep-MI/FastSurfer/files/11139845/pip_freeze_colab.txt)

**Comment by LeHenschel** [comment] 2023-04-03 15:49
It seems to be colab dependent. With the same environment it works fine in jupyter notebook. Also some widgets work in colab, but the one we are using @widgets.interact_manual is not. Upgrading the ipywidgets makes the issue worse in colab (no output, not even selection window is shown).

**Comment by agirodi** [comment] 2023-04-04 11:13
I managed to get it to work by installing the FS requirements and then up/downgrading Numpy and Pillow. Sadly, the installation takes a few minutes and its sometimes didn't work for me. (Could have been some previous changes, that were saved in cookies or something, since it did work on a completely fresh runtime)

```
! pip install -r requirements.txt
! pip install Pillow==7.1.2
! pip install numpy==1.21.6
```

**Comment by LeHenschel** [comment] 2023-04-04 11:33
Would be good to know what changed in these versions that creates the issues. Ideally, we should/can adapt the code to also work with the newer dependencies.

**Comment by agirodi** [comment] 2023-04-04 12:14
> Ideally, we should/can adapt the code to also work with the newer dependencies.

Alternatively we can save the current packages (`pip freeze > requirements_collab.txt`) so that we don't have to repeatedly update the tutorial, whenever google decides to upgrade something. Not the finest solution, because of the installation time, but it is now the second time in 3 or 4 months, we have problems related to dependencies. (Last time it was torchio and yacs that had the wrong versions)

**Comment by LeHenschel** [comment] 2023-04-04 14:06
I do not think this will work well, because a.) the first part runs fastsurfer and therefore might break if the dependencies are not up to date and b.) this introduces a second .txt file we need to keep track off. Not sure what an ideal solution would be but adapting the code to work with the existing dependencies is preferred in my opinion.

**Comment by shijinknox007** [comment] 2023-04-05 05:29
! pip install -r requirements.txt
! pip install Pillow==7.1.2
! pip install numpy==1.21.6
This fix worked for me with the example data .. let me try with custom data ...

**Comment by agirodi** [comment] 2023-05-16 10:44
I just found a better solution, by downgrading plotly to 5.9.0:
`! pip install plotly==5.9.0`
This should make the interact work again.
The requirements.txt has this version of plotly as well, which is why it worked with the other fix.

**Comment by LeHenschel** [comment] 2023-05-19 10:49
The workaround solution suggested by @agirodi was merged into dev. Therefore this issue is fixed for now and I am closing it. Feel free to reopen, if the problem occurs again.

**Closed as completed by LeHenschel** 2023-05-19 10:49 UTC
Labels: needs-fix
