### ISSUE TITLE
Missing BUILD.info crashes fastsurfer, when run locally

### ISSUE THREAD

**Issue by ClePol** [Deep-MI/FastSurfer#468] opened 2024-03-04 13:03 UTC
## Description
The BUILD.info is read in FastSurferCNN/version.py with no fallback, but is created only when building a docker image.
This prevents local installs of FastSurfer from working out-of-the-box.

## Steps to Reproduce
execute run_fastsurfer.sh with any T1w image, without having built a docker container in the repository

## Expected Behavior
There should be a fallback that logs the local system info / git hash if BUID.info does not exist. 

## Environment
FastSurfer 2.2.0
FreeSurfer Version: 7.4.1
OS: Ubuntu 22.04.3 LTS

**Comment by dkuegler** [comment] 2024-03-06 19:16
I cannot really reproduce this issue. If I run `run_fastsurfer.sh --version all`, but there is no `BUILD.info` file the behavior is as expected. Same for running `FastSurferCNN/version.py` ... note, that this is true as long as `--prefer_cache` is not specified.

Please post you exact command line arguments.

**Comment by ClePol** [comment] 2024-03-08 11:22
I was able to reproduce it after trying a view variants - running version.py crashes when git is not installed or the .git folder is not present and the BUILD.info isn't as well. I couldn't identify any other cases - not sure why this would have been triggered on my machine.

Since this is such an edge case, I think we could just exit with an error message and list git as a dependency when running locally - some people might run locally and download FastSurfer via the Release page.

To prevent any crashes in edge cases maybe we could also consider adding an except to https://github.com/Deep-MI/FastSurfer/blob/e483669a6fd16fac10118e57305141df27c70a5c/FastSurferCNN/version.py#L355 and writing an unknown version if opening the file fails.

**Comment by dkuegler** [comment] 2024-03-08 11:44
That makes sense... maybe there should be a more clear error message then. because to print the version, either git or the BUILD.info is needed. I'll loo into that.

**Comment by m-reuter** [comment] 2024-03-08 12:29
If people run a release version, it should not need git, and it has of course a release version number.

**Comment by dkuegler** [comment] 2024-03-08 16:27
Ideally, our releases would then have a build.info file.  It I fixed it so that defaults to gut hash 0000000 and be qnch release...

**Comment by dkuegler** [comment] 2024-03-13 17:15
This should be fixed with #477 and #482.

**Closed as completed by dkuegler** 2024-03-13 17:15 UTC
